spring:
  #数据库连接
  datasource:
    url: jdbc:mysql://218.28.133.52:7111/rjcloud_cms_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: HOLIDAY{Bu18EI06mLvLoP3RbcysHgiU3aRUg7TLVhUEDCV1+N3Z6f4jTSF3bDbrsxqxFxC76cciOpinflaj0iWSH+06YAXsV2FCMMKkBE9f/qPVyYmgjPIq9Pk7ghW+n8BLQhwKXjH7LWDMQx53IB8ydEY6jJhKDoFjMyg5AwPQiAUy5qE=}
    password: HOLIDAY{ozXpz5SOns7t912lMEO4yH3nyiOtl4Uxa8oY3/HQdK+MHG7UHz/JKAiUSbMTuXT3d9LCbs7GjPe6xlwFT0BwvmR5ffvbw4tb2xtWIsTJf8xAbFAuS6osWVt02yJdfsYdDt54npTvHJ/fZVJ8FS8NTXpNsPzyFnywDQQi0vHiJG0=}
  #redis
  redis:
    host: 218.28.133.52
#    password: 123456
    port: 7113
    timeout: 5000
    lettuce:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 20
        min-idle: 0
  servlet:
    multipart:
      resolve-lazily: true
      max-file-size: 500MB
      max-request-size: 500MB

server:
  tomcat:
    max-swallow-size: -1

#文件存储路径
file:
  path: D:\other\file
  avator: /avator
  download: /download
  upload: /upload
  # 文件大小 /M
  maxSize: 100
  avatarMaxSize: 50
  localUrl: http://127.0.0.1:8088
  static:
    folder: D://study/frame/cms/html/path
# swagger开关
swagger:
  enable: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


xxl:
  job:
    admin:
      #### 调度中心部署跟地址 [选填]：如调度中心集群部署存在多个地址则用逗号分隔。执行器将会使用该地址进行"执行器心跳注册"和"任务结果回调"；为空则关闭自动注册；
      addresses: http://127.0.0.1:8080/xxl-job-admin
      ### 执行器通讯TOKEN [选填]：非空时启用
    accessToken: 9A3CFFD2113813559663B1D1612FBE2E
    ### 执行器AppName [选填]：执行器心跳注册分组依据；为空则关闭自动注册
    executor:
      appname: cms-task
      ### 执行器注册 [选填]：优先使用该配置作为注册地址，为空时使用内嵌服务 ”IP:PORT“ 作为注册地址。从而更灵活的支持容器类型执行器动态IP和动态映射端口问题。
      address:
      ### 执行器IP [选填]：默认为空表示自动获取IP，多网卡时可手动设置指定IP，该IP不会绑定Host仅作为通讯实用；地址信息用于 "执行器注册" 和 "调度中心请求并触发任务"；
      ip:
      ### 执行器端口号 [选填]：小于等于0则自动获取；默认端口为9999，单机部署多个执行器时，注意要配置不同执行器端口
      port: 9998
      ### 执行器运行日志文件存储磁盘路径 [选填] ：需要对该路径拥有读写权限；为空则使用默认路径；
      logpath: ../xxl-job/jobhandler
      ### 执行器日志文件保存天数 [选填] ： 过期日志自动清理, 限制值大于等于3时生效; 否则, 如-1, 关闭自动清理功能；
      logretentiondays: 30